### ISSUE TITLE
Add sprinting

### ISSUE THREAD

**Issue by coxg** [coxg/Generator#10]
Likely depends on #8, since we'll need some concept of animations and time taken before we can make someone move more quickly. 

Either way, we'll want this to drain stamina (or energy if they're a robot) in order to move more quickly. Worry about making it pretty later.

**Comment by Hrosek** [comment]
No difference in speed when pressing left shift and when not pressing left shift.  I think the walking animation may have overwritten this.

**Comment by Hrosek** [comment]
This got shifted to 1, see the ability ticket
