### ISSUE TITLE
Add an "Animation" class

### ISSUE THREAD

**Issue by coxg** [coxg/Generator#14]
Should look something like the following:

public class Animation
- [x] string Name,
- [x] GameObject SourceObject
- [x] int Duration,
- [x] Action Start,
- [x] Action OnUpdate,
- [x] Action Stop

Maybe we don't need Duration, I dunno. Also we need to have some way of updating them on each update and killing them when they're no longer being used. Figure it out!

Also, remember to update GameObject.cs and Ability.cs with whatever we figure out.

**Comment by coxg** [comment]
Wound up going with a slightly different approach from above. See the 'Frames' and 'Animation' classes in Animation.cs, as well as the examples in GameObject.cs. So far animations have been added for 'Sprint' and 'Always Sprint'. These will likely need to be tinkered with slightly once we have GameComponents up and running.

Note that ArrayUtil.cs, Spline.cs, and TriDiagonalMatrix.cs are essentially copy/pasted from an external source. I believe there's open permissions to do whatever we want with the files, but we'll at the very least want to alter these to be more suited to what we're doing. Right now applying these functions is relatively expensive, though we're only doing it upon instantiation.

**Comment by Hrosek** [comment]
I tested the 1 and 3 keys before and after dialog and rotation, and nothing broke.
