### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by coxg** [coxg/Generator#15]
We appear to have a memory leak. Already. Yikes!

Here's what performance looks like when we're getting started:
http://puu.sh/zwrnY/0244b1d7c0.png

This keeps on growing at a steady rate (roughly 1 MB/second), tested up to almost a gig at 10 minutes. Looks like this is caused by the ContentManager:
http://puu.sh/zwrkG/57ce17523f.png

Doing a bit of digging brought me to the following answer:
```So most likely this is a memory leak somewhere in your draw() function.
There are a few classes that you absolutely cannot create new instances of for every frame (without deleting the old ones) - SpriteBatch, Texture2D, RenderTarget etc.
These should be created once and then reused, because the garbage collector does not remove them from memory. You need to do that manually with .Dispose()
Check if you create them every frame!
```
I have no idea if I've been careful about that (almost definitely not), so we'll need to do some digging. The best solution would include reusing the loaded content, but another potential solution might include manually garbage collecting with .Dispose().

**Comment by coxg** [comment]
Fixed:
http://puu.sh/zAovP/9751cf8f57.png

It was exactly what the link said, I wasn't disposing a drawing asset. Turns out it was a BasicEffect.

**Comment by Hrosek** [comment]
I ran this for upwards of half an hour and so far memory usage looks steady & nothing's crashed.
